import type { Backpack } from '~/types/backpack'

/**
 * Hand-written development fixtures — three `Backpack` values for building and
 * testing components before research (Phase 5) or ingest (Phase 4) exists.
 *
 * These are NOT catalog content. ADR-009's ban on synthetic data and imagery
 * governs `app/data/catalog.json`, which is generated by `pnpm ingest` from
 * researched sources; this file is a component harness. Phase 3's
 * `app/pages/index.vue` imports it because no catalog exists yet; Phase 6
 * swaps that import for `catalog.json`. It must never ship as catalog data.
 *
 * Image paths follow the real ingest convention (`/images/{slug}/{n}`, with
 * `-{w}.{avif,webp}` appended by the carousel), but nothing renders: no files
 * exist under `public/images/` until ingest runs, and that directory is
 * gitignored (ADR-012). Broken images here are expected.
 *
 * The set is chosen to exercise the edge cases the card layout has to survive:
 *
 * | Fixture              | Colorways | Images | Scale | Exercises                                  |
 * | -------------------- | --------- | ------ | ----- | ------------------------------------------ |
 * | Aer Travel Pack 3    | 3         | 5      | 5.0   | ghost padding (5 empty cells); full carousel|
 * | GORUCK GR1 26L       | 8         | 1      | 10.0  | exact 8-cell fill, no pager; n=1 carousel   |
 * | Topo Designs Rover   | 15        | 3      | 5.0   | 3-page wrapping pager, partial last page    |
 *
 * Why each edge case matters:
 * - **3 / 8 / 15 colorways** hit all three ColorwayGrid paths (ADR-015): ghost
 *   padding, the exact-fill boundary where the pager must NOT appear, and
 *   paging where `ceil(15 / 7) = 3` and the final page holds a single colorway
 *   with the pager still pinned to cell 8.
 * - **1 image** is the case that breaks naive carousel arithmetic: prev/next
 *   must resolve to the same image via modulo, never index -1 (ADR-016).
 * - **Both review scales** are present, so any sort or filter that forgets to
 *   normalize `score / scale` produces visibly wrong ordering rather than
 *   passing by luck.
 * - **Topo's long model name** overflows band 2 at the 260px minimum card
 *   width, exercising the `truncate` that keeps the 65/15/20 split exact
 *   (ADR-021).
 */
export const fixtureBackpacks: Backpack[] = [
  {
    rank: 4,
    slug: 'aer-travel-pack-3',
    name: 'Travel Pack 3',
    brand: 'Aer',
    // 5 images — the documented maximum; exercises the carousel at full length.
    images: [0, 1, 2, 3, 4].map((n) => ({
      base: `/images/aer-travel-pack-3/${n}`,
      widths: [640, 1280],
      width: 1280,
      height: 1280,
      alt: `Aer Travel Pack 3 — view ${n + 1} of 5`,
    })),
    // 3 colorways — ColorwayGrid ghost-pads the remaining 5 cells, no pager.
    colorways: [
      { name: 'Black', hex: '#171719', family: 'black' },
      { name: 'Gray', hex: '#8b8d90', family: 'grey' },
      { name: 'Navy', hex: '#22304a', family: 'navy' },
    ],
    price: {
      amountUsd: 249,
      retailer: 'REI',
      url: 'https://www.rei.com/product/000001/aer-travel-pack-3',
      capturedAt: '2026-09-01',
    },
    // 5.0 scale (retailer star rating).
    review: {
      score: 4.4,
      scale: 5.0,
      source: 'REI',
      url: 'https://www.rei.com/product/000001/aer-travel-pack-3#reviews',
      capturedAt: '2026-09-01',
    },
    specs: {
      capacityLiters: 28,
      weightGrams: 1560,
      dimensions: '21.5 x 13 x 8 in',
      material: '1680D Cordura ballistic nylon',
    },
  },
  {
    rank: 3,
    slug: 'goruck-gr1-26l',
    name: 'GR1 26L',
    brand: 'GORUCK',
    // Exactly 1 image — prev and next must both land back on index 0 (modulo,
    // not clamping), and the carousel must not render a dot strip of one.
    images: [
      {
        base: '/images/goruck-gr1-26l/0',
        widths: [640, 1280],
        width: 1280,
        height: 1280,
        alt: 'GORUCK GR1 26L in black, three-quarter front view',
      },
    ],
    // Exactly 8 colorways — the boundary case: the grid fills every cell and
    // must still show no pager, since 8 <= 8.
    colorways: [
      { name: 'Black', hex: '#141414', family: 'black' },
      { name: 'Wolf Grey', hex: '#7c8085', family: 'grey' },
      { name: 'Ranger Green', hex: '#4a5240', family: 'green' },
      { name: 'Coyote Brown', hex: '#7d6144', family: 'brown' },
      { name: 'Navy', hex: '#1f2b40', family: 'navy' },
      { name: 'Steel', hex: '#5a6673', family: 'blue' },
      { name: 'Multicam', hex: '#8a7c5c', family: 'multi' },
      { name: 'Oxblood', hex: '#5c2027', family: 'red' },
    ],
    price: {
      amountUsd: 395,
      retailer: 'GORUCK',
      url: 'https://www.goruck.com/products/gr1-26l',
      capturedAt: '2026-08-28',
    },
    // 10.0 scale (enthusiast review site) — pairs with the 5.0 fixtures to make
    // unnormalized sorting fail loudly.
    review: {
      score: 9.2,
      scale: 10.0,
      source: 'Carryology',
      url: 'https://www.carryology.com/reviews/goruck-gr1-26l/',
      capturedAt: '2026-08-28',
    },
    specs: {
      capacityLiters: 26,
      weightGrams: 1420,
      dimensions: '20 x 12 x 7.5 in',
      material: '1000D Cordura',
    },
  },
  {
    rank: 13,
    slug: 'topo-designs-rover-pack-tech',
    // Intentionally long: overflows band 2 at the 260px minimum card width and
    // must `truncate` rather than wrap (ADR-021).
    name: 'Rover Pack Tech Recycled Nylon Daypack',
    brand: 'Topo Designs',
    images: [0, 1, 2].map((n) => ({
      base: `/images/topo-designs-rover-pack-tech/${n}`,
      widths: [640, 1280],
      width: 1280,
      height: 1280,
      alt: `Topo Designs Rover Pack Tech — view ${n + 1} of 3`,
    })),
    // 15 colorways — ceil(15 / 7) = 3 pages of 7 + 7 + 1. The third page shows
    // one swatch, six ghost cells, and the pager still in cell 8; `>` from
    // there wraps to page 1 (ADR-015, ADR-016).
    colorways: [
      { name: 'Black', hex: '#1b1b1b', family: 'black' },
      { name: 'Charcoal', hex: '#4a4a4d', family: 'grey' },
      { name: 'Bone White', hex: '#e6e1d6', family: 'white' },
      { name: 'Navy', hex: '#26334d', family: 'navy' },
      { name: 'Pond Blue', hex: '#3f7fa6', family: 'blue' },
      { name: 'Forest', hex: '#25402f', family: 'green' },
      { name: 'Botanic Green', hex: '#6f8f5e', family: 'green' },
      { name: 'Olive', hex: '#5d5c36', family: 'olive' },
      { name: 'Desert Palm', hex: '#8f8a63', family: 'olive' },
      { name: 'Khaki', hex: '#bda77f', family: 'tan' },
      { name: 'Peppercorn', hex: '#5b4636', family: 'brown' },
      { name: 'Burgundy', hex: '#6b2333', family: 'red' },
      { name: 'Clay', hex: '#c1663f', family: 'orange' },
      { name: 'Plum', hex: '#5a3a63', family: 'purple' },
      { name: 'Geo Print', hex: '#9a6b4f', family: 'multi' },
    ],
    price: {
      amountUsd: 139,
      retailer: 'Backcountry',
      url: 'https://www.backcountry.com/topo-designs-rover-pack-tech',
      capturedAt: '2026-08-30',
    },
    review: {
      score: 4.7,
      scale: 5.0,
      source: 'Backcountry',
      url: 'https://www.backcountry.com/topo-designs-rover-pack-tech#reviews',
      capturedAt: '2026-08-30',
    },
    specs: {
      capacityLiters: 20,
      weightGrams: 880,
      dimensions: '18 x 11.5 x 6 in',
      material: '100% recycled 400D nylon',
    },
  },
]
